In [4]:
import torch

In [5]:
torch.version.__version__

'2.3.1+cpu'

In [6]:
# 创建一个3 * 3 的张量 并且每个元素都是1
a = torch.ones(3, 3)
a

F:\CSProjects\PycharmProjects\study_projects\pytorch_project\.venv\Lib\site-packages\torch\_tensor_str.py:138: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)
  tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0)


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [8]:
b = torch.ones(3, 3)
b

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [9]:
a + b

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [10]:
torch.cuda.is_available()

False

In [11]:
a = a.to('cuda')

AssertionError: Torch not compiled with CUDA enabled